gis_drf_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
이미지 출력
static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

profileapp/models.py
import sys
from io import BytesIO
from PIL import Image

from django.contrib.auth.models import User
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver

from image_processing import thumbnail


class Profile(models.Model):
    owner = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)

    nickname = models.CharField(max_length=50, null=False)
    image = models.ImageField(upload_to='profile/', null=True, blank=True)
    thumb = models.ImageField(upload_to='profile/thumbnail/', null=True)
    message = models.CharField(max_length=255, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    # https://docs.djangoproject.com/en/4.0/ref/models/instances/#saving-objects
    # https://docs.djangoproject.com/en/4.0/topics/db/models/#overriding-model-methods
    def save(self, *args, **kwargs):
        # 썸네일 생성 로직 필요
        self.generate_thumbnail()
        super().save(*args, **kwargs)

    def generate_thumbnail(self):
        """
        썸네일 생성 메서드
        https://pillow.readthedocs.io/en/stable/reference/Image.html
        https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.thumbnail
        """
        # 먼저 사용자가 이미지를 업로드했는지 확인
        if self.image:
            # 새로 만들어준 image_processing의 thumbnail.py를 불러오는 것 (패키지로 별도 분리)
            output = thumbnail.generate_thumbnail(self.image)

            # 장고에서 제공하는 메모리 내 이미지 파일을
            # 장고 파일 객체로 인식하게 도와주는 InMemoryUploadedFile 클래스를 이용해서
            # 이미지를 읽고, self.thumb 컬럼에 해당 변형된 이미지를 할당합니다
            self.thumb = InMemoryUploadedFile(output, 'ImageField', self.image.name,
                                              'image/jpeg', sys.getsizeof(output), None)


# django signals
# https://docs.djangoproject.com/en/3.2/topics/signals/
@receiver(post_save, sender=User)
def create_profile(sender, instance=None, created=False, **kwargs):
    if created:
        Profile.objects.create(owner=instance, nickname='-Nick-')

profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'image', 'message']

profileapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from profileapp.decorators import profile_ownership_required
from profileapp.forms import ProfileCreationForm
from profileapp.models import Profile


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ProfileCreateView(CreateView):
    model = Profile
    form_class = ProfileCreationForm
    template_name = 'profileapp/create.html'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.owner.pk})


@method_decorator(profile_ownership_required, 'get')
@method_decorator(profile_ownership_required, 'post')
class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileCreationForm
    context_object_name = 'target_profile'
    template_name = 'profileapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.owner.pk})

profileapp/templates/profileapp/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

    <div class="my-5" style="max-width: 600px; margin: auto">

        <div class="my-5">
            <h2>Create Profile</h2>
        </div>

        <form action="{% url 'profileapp:create' %}"
              method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill px-5">
        </form>

    </div>

{% endblock %}

profileapp/templates/profileapp/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

    <div class="my-5" style="max-width: 600px; margin: auto;">

        <div class="my-5">
            <h3>Update Profile</h3>
        </div>

        <div>
            <form action="{% url 'profileapp:update' pk=target_profile.pk %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill px-5">
            </form>
        </div>

    </div>

{% endblock %}